# Generated by Django 4.2.5 on 2023-09-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
