# Generated by Django 4.2.5 on 2023-09-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_reserva_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nome_pet',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
